libopencm3: rtc.c File Reference
rtc.c File Reference
#include <libopencm3/stm32/exti.h>
#include <libopencm3/cm3/nvic.h>
#include <libopencm3/stm32/rtc.h>
Functions
void rtc_enable_wakeup_timer (void)
Enable the wakeup timer.
void rtc_disable_wakeup_timer (void)
Disable the wakeup timer.
void rtc_enable_wakeup_timer_interrupt (void)
Enable the wakeup timer interrupt.
void rtc_disable_wakeup_timer_interrupt (void)
Disable the wakeup timer interrupt.
Function Documentation
void rtc_disable_wakeup_timer (void)
Disable the wakeup timer.
Warning
You must unlock the registers before using this function
Definition at line 52 of file rtc.c.
References RTC_CR, RTC_CR_WUTE, and rtc_disable_wakeup_timer_interrupt().
void rtc_disable_wakeup_timer_interrupt (void)
Disable the wakeup timer interrupt.
Warning
You must unlock the registers before using this function
Definition at line 87 of file rtc.c.
References EXTI22, exti_disable_request(), nvic_disable_irq(), NVIC_RTC_WKUP_IRQ, RTC_CR, and RTC_CR_WUTIE.
Referenced by rtc_disable_wakeup_timer().
void rtc_enable_wakeup_timer (void)
Enable the wakeup timer.
Warning
You must unlock the registers before using this function
Definition at line 41 of file rtc.c.
References RTC_CR, RTC_CR_OSEL_SHIFT, RTC_CR_OSEL_WAKEUP, RTC_CR_WUTE, and rtc_enable_wakeup_timer_interrupt().
void rtc_enable_wakeup_timer_interrupt (void)
Enable the wakeup timer interrupt.
Warning
You must unlock the registers before using this function
Definition at line 63 of file rtc.c.
References EXTI22, exti_enable_request(), exti_set_trigger(), EXTI_TRIGGER_RISING, nvic_enable_irq(), NVIC_RTC_WKUP_IRQ, nvic_set_priority(), RTC_CR, and RTC_CR_WUTIE.
Referenced by rtc_enable_wakeup_timer().