libopencm3: usb_efm32hg.c File Reference
usb_efm32hg.c File Reference
#include <string.h>
#include <libopencm3/cm3/common.h>
#include <libopencm3/efm32/memorymap.h>
#include <libopencm3/efm32/cmu.h>
#include <libopencm3/efm32/usb.h>
#include <libopencm3/usb/usbd.h>
#include <libopencm3/usb/dwc/otg_fs.h>
#include "usb_private.h"
#include "usb_dwc_common.h"
Macros
#define RX_FIFO_SIZE 256
#define ENDPOINT_COUNT 4
Functions
static usbd_device * efm32hg_usbd_init (void)
Initialize the USB device controller hardware of the EFM32HG.
Variables
static struct _usbd_device _usbd_dev
const struct _usbd_driver efm32hg_usb_driver
Macro Definition Documentation
#define ENDPOINT_COUNT 4
Definition at line 37 of file usb_efm32hg.c.
#define RX_FIFO_SIZE 256
Definition at line 32 of file usb_efm32hg.c.
Function Documentation
static usbd_device* efm32hg_usbd_init (void) static
Initialize the USB device controller hardware of the EFM32HG.
Definition at line 42 of file usb_efm32hg.c.
References _usbd_dev, CMU_LE, CMU_LFCLKSEL, CMU_LFCLKSEL_LFC_LFRCO, cmu_osc_on(), cmu_periph_clock_enable(), cmu_set_usbclk_source(), CMU_USB, CMU_USBC, CMU_USBCRCTRL, CMU_USBCRCTRL_EN, CMU_USBLE, CMU_USHFRCOCONF, CMU_USHFRCOCONF_BAND_48MHZ, cmu_wait_for_osc_ready(), cmu_wait_for_usbclk_selected(), efm32hg_usb_driver, OTG_DCFG_DSPD, OTG_DCTL_SDIS, OTG_DIEPMSK_XFRCM, OTG_FS_DAINTMSK, OTG_FS_DCFG, OTG_FS_DCTL, OTG_FS_DIEPMSK, OTG_FS_GAHBCFG, OTG_FS_GINTMSK, OTG_FS_GINTSTS, OTG_FS_GRSTCTL, OTG_FS_GRXFSIZ, OTG_FS_GUSBCFG, OTG_FS_PCGCCTL, OTG_GAHBCFG_GINT, OTG_GINTMSK_ENUMDNEM, OTG_GINTMSK_IEPINT, OTG_GINTMSK_RXFLVLM, OTG_GINTMSK_USBSUSPM, OTG_GINTMSK_WUIM, OTG_GINTSTS_MMIS, OTG_GRSTCTL_AHBIDL, OTG_GRSTCTL_CSRST, OTG_GUSBCFG_FDMOD, OTG_GUSBCFG_TRDT_MASK, USB_CTRL, USB_ROUTE, USB_ROUTE_PHYPEN, and USHFRCO.
Variable Documentation
struct _usbd_device _usbd_dev static
Definition at line 39 of file usb_efm32hg.c.
Referenced by efm32hg_usbd_init().