libopencm3: Flash_defines
Flash_defines
Modules
Flash programming width
Macros
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
#define FLASH_OPTCR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
#define FLASH_OPTCR1 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x18)
#define FLASH_KEYR_KEY1 0x45670123UL
#define FLASH_KEYR_KEY2 0xcdef89abUL
#define FLASH_OPTKEYR_KEY1 0x08192a3bUL
#define FLASH_OPTKEYR_KEY2 0x4c5d6e7fUL
#define FLASH_ACR_ARTRST (1 << 11)
#define FLASH_ACR_ARTEN (1 << 9)
#define FLASH_ACR_PRFTEN (1 << 8)
#define FLASH_ACR_LATENCY_MASK 0x0f
#define FLASH_SR_BSY (1 << 16)
#define FLASH_SR_ERSERR (1 << 7)
#define FLASH_SR_PGPERR (1 << 6)
#define FLASH_SR_PGAERR (1 << 5)
#define FLASH_SR_WRPERR (1 << 4)
#define FLASH_SR_OPERR (1 << 1)
#define FLASH_SR_EOP (1 << 0)
#define FLASH_CR_LOCK (1 << 31)
#define FLASH_CR_ERRIE (1 << 25)
#define FLASH_CR_EOPIE (1 << 24)
#define FLASH_CR_STRT (1 << 16)
#define FLASH_CR_PROGRAM_MASK 0x3
#define FLASH_CR_PROGRAM_SHIFT 8
#define FLASH_CR_SNB_SHIFT 3
#define FLASH_CR_SNB_MASK 0x1f
#define FLASH_CR_MER (1 << 2)
#define FLASH_CR_SER (1 << 1)
#define FLASH_CR_PG (1 << 0)
#define FLASH_OPTCR_IWDG_STOP (1 << 31)
#define FLASH_OPTCR_IWDG_STDBY (1 << 30)
#define FLASH_OPTCR_NWRP_SHIFT 16
#define FLASH_OPTCR_NWRP_MASK 0xff
#define FLASH_OPTCR_RDP_SHIFT 8
#define FLASH_OPTCR_RDP_MASK 0xff
#define FLASH_OPTCR_NRST_STDBY (1 << 7)
#define FLASH_OPTCR_NRST_STOP (1 << 6)
#define FLASH_OPTCR_IWDG_SW (1 << 5)
#define FLASH_OPTCR_WWDG_SW (1 << 4)
#define FLASH_OPTCR_BOR_LEV_MASK 3
#define FLASH_OPTCR_BOR_LEV_SHIFT 2
#define FLASH_OPTCR_BOR_LEV_3 0x00
#define FLASH_OPTCR_BOR_LEV_2 0x01
#define FLASH_OPTCR_BOR_LEV_1 0x02
#define FLASH_OPTCR_BOR_OFF 0x03
#define FLASH_OPTCR_OPTSTRT (1 << 1)
#define FLASH_OPTCR_OPTLOCK (1 << 0)
#define FLASH_OPTCR1_BOOT_ADD1_MASK 0xffff
#define FLASH_OPTCR1_BOOT_ADD1_SHIFT 16
#define FLASH_OPTCR1_BOOT_ADD0_MASK 0xffff
#define FLASH_OPTCR1_BOOT_ADD0_SHIFT 0
Functions
void flash_set_ws (uint32_t ws)
Set the Number of Wait States.
void flash_unlock (void)
Unlock the Flash Program and Erase Controller.
void flash_lock (void)
Lock the Flash Program and Erase Controller.
void flash_clear_pgperr_flag (void)
Clear the Programming Error Status Flag.
void flash_clear_eop_flag (void)
Clear the End of Operation Status Flag.
void flash_wait_for_last_operation (void)
Wait until Last Operation has Ended.
void flash_unlock_option_bytes (void)
Unlock the Option Byte Access.
void flash_lock_option_bytes (void)
Lock the Option Byte Access.
void flash_clear_erserr_flag (void)
Clear the Erase Sequence Error Flag.
void flash_clear_wrperr_flag (void)
Clear the Write Protect Error Flag.
void flash_clear_pgaerr_flag (void)
Clear the Programming Alignment Error Flag.
void flash_art_enable (void)
Enable the ART Cache.
void flash_art_disable (void)
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
void flash_art_reset (void)
Reset the ART Cache.
void flash_clear_status_flags (void)
Clear All Status Flags.
void flash_erase_all_sectors (uint32_t program_size)
Erase All FLASH.
void flash_erase_sector (uint8_t sector, uint32_t program_size)
Erase a Sector of FLASH.
void flash_program_double_word (uint32_t address, uint64_t data)
Program a 64 bit Word to FLASH.
void flash_program_word (uint32_t address, uint32_t data)
Program a 32 bit Word to FLASH.
void flash_program_half_word (uint32_t address, uint16_t data)
Program a Half Word to FLASH.
void flash_program_byte (uint32_t address, uint8_t data)
Program an 8 bit Byte to FLASH.
void flash_program (uint32_t address, uint8_t *data, uint32_t len)
Program a Data Block to FLASH.
void flash_program_option_bytes (uint32_t data)
Program the Option Bytes.
Detailed Description
Author
© 2017 Matthew Lai m@mat.nosp@m.thew.nosp@m.lai.c.nosp@m.a
© 2010 Thomas Otto tommi.nosp@m.@via.nosp@m.dmin..nosp@m.org
© 2010 Mark Butler mbutl.nosp@m.er@p.nosp@m.hysic.nosp@m.s.ot.nosp@m.ago.a.nosp@m.c.nz
Macro Definition Documentation
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
Definition at line 62 of file f7/flash.h.
Referenced by flash_art_enable(), flash_art_reset(), flash_prefetch_disable(), flash_prefetch_enable(), and flash_set_ws().
#define FLASH_ACR_ARTEN (1 << 9)
Definition at line 80 of file f7/flash.h.
Referenced by flash_art_enable().
#define FLASH_ACR_ARTRST (1 << 11)
Definition at line 79 of file f7/flash.h.
Referenced by flash_art_reset().
#define FLASH_ACR_LATENCY_MASK 0x0f
Definition at line 83 of file f7/flash.h.
Referenced by flash_set_ws().
#define FLASH_ACR_PRFTEN (1 << 8)
Definition at line 81 of file f7/flash.h.
Referenced by flash_prefetch_disable(), and flash_prefetch_enable().
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
Definition at line 66 of file f7/flash.h.
Referenced by flash_erase_all_sectors(), flash_erase_sector(), flash_lock(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), flash_program_word(), flash_set_program_size(), and flash_unlock().
#define FLASH_CR_EOPIE (1 << 24)
Definition at line 99 of file f7/flash.h.
#define FLASH_CR_ERRIE (1 << 25)
Definition at line 98 of file f7/flash.h.
#define FLASH_CR_LOCK (1 << 31)
Definition at line 97 of file f7/flash.h.
Referenced by flash_lock(), and flash_unlock().
#define FLASH_CR_MER (1 << 2)
Definition at line 116 of file f7/flash.h.
Referenced by flash_erase_all_sectors().
#define FLASH_CR_PG (1 << 0)
Definition at line 118 of file f7/flash.h.
Referenced by flash_program_byte(), flash_program_double_word(), flash_program_half_word(), and flash_program_word().
#define FLASH_CR_PROGRAM_MASK 0x3
Definition at line 102 of file f7/flash.h.
Referenced by flash_set_program_size().
#define FLASH_CR_PROGRAM_SHIFT 8
Definition at line 103 of file f7/flash.h.
Referenced by flash_set_program_size().
#define FLASH_CR_SER (1 << 1)
Definition at line 117 of file f7/flash.h.
Referenced by flash_erase_sector().
#define FLASH_CR_SNB_MASK 0x1f
Definition at line 114 of file f7/flash.h.
Referenced by flash_erase_sector().
#define FLASH_CR_SNB_SHIFT 3
Definition at line 113 of file f7/flash.h.
Referenced by flash_erase_sector().
#define FLASH_CR_STRT (1 << 16)
Definition at line 100 of file f7/flash.h.
Referenced by flash_erase_all_sectors(), and flash_erase_sector().
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
Definition at line 63 of file f7/flash.h.
Referenced by flash_unlock().
#define FLASH_KEYR_KEY1 0x45670123UL
Definition at line 72 of file f7/flash.h.
Referenced by flash_unlock().
#define FLASH_KEYR_KEY2 0xcdef89abUL
Definition at line 73 of file f7/flash.h.
Referenced by flash_unlock().
#define FLASH_OPTCR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
Definition at line 67 of file f7/flash.h.
Referenced by flash_lock_option_bytes(), flash_program_option_bytes(), and flash_unlock_option_bytes().
#define FLASH_OPTCR1 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x18)
Definition at line 68 of file f7/flash.h.
#define FLASH_OPTCR1_BOOT_ADD0_MASK 0xffff
Definition at line 149 of file f7/flash.h.
#define FLASH_OPTCR1_BOOT_ADD0_SHIFT 0
Definition at line 150 of file f7/flash.h.
#define FLASH_OPTCR1_BOOT_ADD1_MASK 0xffff
Definition at line 147 of file f7/flash.h.
#define FLASH_OPTCR1_BOOT_ADD1_SHIFT 16
Definition at line 148 of file f7/flash.h.
#define FLASH_OPTCR_BOR_LEV_1 0x02
Definition at line 140 of file f7/flash.h.
#define FLASH_OPTCR_BOR_LEV_2 0x01
Definition at line 139 of file f7/flash.h.
#define FLASH_OPTCR_BOR_LEV_3 0x00
Definition at line 138 of file f7/flash.h.
#define FLASH_OPTCR_BOR_LEV_MASK 3
Definition at line 136 of file f7/flash.h.
#define FLASH_OPTCR_BOR_LEV_SHIFT 2
Definition at line 137 of file f7/flash.h.
#define FLASH_OPTCR_BOR_OFF 0x03
Definition at line 141 of file f7/flash.h.
#define FLASH_OPTCR_IWDG_STDBY (1 << 30)
Definition at line 123 of file f7/flash.h.
#define FLASH_OPTCR_IWDG_STOP (1 << 31)
Definition at line 122 of file f7/flash.h.
#define FLASH_OPTCR_IWDG_SW (1 << 5)
Definition at line 133 of file f7/flash.h.
#define FLASH_OPTCR_NRST_STDBY (1 << 7)
Definition at line 131 of file f7/flash.h.
#define FLASH_OPTCR_NRST_STOP (1 << 6)
Definition at line 132 of file f7/flash.h.
#define FLASH_OPTCR_NWRP_MASK 0xff
Definition at line 126 of file f7/flash.h.
#define FLASH_OPTCR_NWRP_SHIFT 16
Definition at line 125 of file f7/flash.h.
#define FLASH_OPTCR_OPTLOCK (1 << 0)
Definition at line 144 of file f7/flash.h.
Referenced by flash_lock_option_bytes(), flash_program_option_bytes(), and flash_unlock_option_bytes().
#define FLASH_OPTCR_OPTSTRT (1 << 1)
Definition at line 143 of file f7/flash.h.
Referenced by flash_program_option_bytes().
#define FLASH_OPTCR_RDP_MASK 0xff
Definition at line 129 of file f7/flash.h.
#define FLASH_OPTCR_RDP_SHIFT 8
Definition at line 128 of file f7/flash.h.
#define FLASH_OPTCR_WWDG_SW (1 << 4)
Definition at line 134 of file f7/flash.h.
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
Definition at line 64 of file f7/flash.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_OPTKEYR_KEY1 0x08192a3bUL
Definition at line 74 of file f7/flash.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_OPTKEYR_KEY2 0x4c5d6e7fUL
Definition at line 75 of file f7/flash.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
Definition at line 65 of file f7/flash.h.
Referenced by flash_clear_eop_flag(), flash_clear_erserr_flag(), flash_clear_pgaerr_flag(), flash_clear_pgperr_flag(), flash_clear_wrperr_flag(), and flash_wait_for_last_operation().
#define FLASH_SR_BSY (1 << 16)
Definition at line 87 of file f7/flash.h.
Referenced by flash_wait_for_last_operation().
#define FLASH_SR_EOP (1 << 0)
Definition at line 93 of file f7/flash.h.
Referenced by flash_clear_eop_flag().
#define FLASH_SR_ERSERR (1 << 7)
Definition at line 88 of file f7/flash.h.
Referenced by flash_clear_erserr_flag().
#define FLASH_SR_OPERR (1 << 1)
Definition at line 92 of file f7/flash.h.
#define FLASH_SR_PGAERR (1 << 5)
Definition at line 90 of file f7/flash.h.
Referenced by flash_clear_pgaerr_flag().
#define FLASH_SR_PGPERR (1 << 6)
Definition at line 89 of file f7/flash.h.
Referenced by flash_clear_pgperr_flag().
#define FLASH_SR_WRPERR (1 << 4)
Definition at line 91 of file f7/flash.h.
Referenced by flash_clear_wrperr_flag().
Function Documentation
void flash_art_disable (void)
void flash_art_enable (void)
Enable the ART Cache.
Definition at line 215 of file flash.c.
References FLASH_ACR, and FLASH_ACR_ARTEN.
Referenced by rcc_clock_setup_hse(), and rcc_clock_setup_hsi().
void flash_art_reset (void)
Reset the ART Cache.
The ART cache must be disabled for this to have effect.
Definition at line 255 of file flash.c.
References FLASH_ACR, and FLASH_ACR_ARTRST.
void flash_clear_eop_flag (void)
Clear the End of Operation Status Flag.
Definition at line 130 of file flash.c.
References FLASH_SR, and FLASH_SR_EOP.
Referenced by flash_clear_status_flags().
void flash_clear_erserr_flag (void)
Clear the Erase Sequence Error Flag.
This flag is set when an erase operation is performed with control register has not been correctly set.
Definition at line 185 of file flash.c.
References FLASH_SR, and FLASH_SR_ERSERR.
Referenced by flash_clear_status_flags().
void flash_clear_pgaerr_flag (void)
Clear the Programming Alignment Error Flag.
Definition at line 195 of file flash.c.
References FLASH_SR, and FLASH_SR_PGAERR.
Referenced by flash_clear_status_flags().
void flash_clear_pgperr_flag (void)
Clear the Programming Error Status Flag.
Definition at line 120 of file flash.c.
References FLASH_SR, and FLASH_SR_PGPERR.
Referenced by flash_clear_status_flags().
void flash_clear_status_flags (void)
Clear All Status Flags.
Program error, end of operation, write protect error.
Definition at line 266 of file flash.c.
References flash_clear_eop_flag(), flash_clear_erserr_flag(), flash_clear_pgaerr_flag(), flash_clear_pgperr_flag(), and flash_clear_wrperr_flag().
void flash_clear_wrperr_flag (void)
Clear the Write Protect Error Flag.
Definition at line 205 of file flash.c.
References FLASH_SR, and FLASH_SR_WRPERR.
Referenced by flash_clear_status_flags().
void flash_erase_all_sectors (uint32_t program_size)
Erase All FLASH.
This performs all operations necessary to erase all sectors in the FLASH memory.
Parameters
program_size 0 (8-bit), 1 (16-bit), 2 (32-bit), 3 (64-bit)
Definition at line 284 of file flash.c.
References FLASH_CR, FLASH_CR_MER, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_erase_sector (uint8_t sector, uint32_t program_size)
Erase a Sector of FLASH.
This performs all operations necessary to erase a sector in FLASH memory. The page should be checked to ensure that it was properly erased. A sector must first be fully erased before attempting to program it.
See the reference manual or the FLASH programming manual for details.
Parameters
[in] sector (0 - 11 for some parts, 0-23 on others)
program_size 0 (8-bit), 1 (16-bit), 2 (32-bit), 3 (64-bit)
Definition at line 309 of file flash.c.
References FLASH_CR, FLASH_CR_SER, FLASH_CR_SNB_MASK, FLASH_CR_SNB_SHIFT, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_lock (void)
Lock the Flash Program and Erase Controller.
Used to prevent spurious writes to FLASH.
Definition at line 110 of file flash.c.
References FLASH_CR, and FLASH_CR_LOCK.
void flash_lock_option_bytes (void)
Lock the Option Byte Access.
This disables write access to the option bytes. It is locked by default on reset.
Definition at line 173 of file flash.c.
References FLASH_OPTCR, and FLASH_OPTCR_OPTLOCK.
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
Note carefully the clock restrictions under which the prefetch buffer may be set to disabled. See the reference manual for details.
Definition at line 244 of file flash.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the clock restrictions under which the prefetch buffer may be enabled or disabled. Changes are normally made while the clock is running in the power-on low frequency mode before being set to a higher speed mode. See the reference manual for details.
Definition at line 232 of file flash.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
Referenced by rcc_clock_setup_hse(), and rcc_clock_setup_hsi().
void flash_program (uint32_t address, uint8_t * data, uint32_t len)
Program a Data Block to FLASH.
This programs an arbitrary length data block to FLASH memory. All the addresses written to must have been erased (by calling flash_erase_sector). The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] address Starting address in Flash.
[in] data Pointer to start of data block.
[in] len Length of data block.
Definition at line 447 of file flash.c.
References flash_program_byte().
void flash_program_byte (uint32_t address, uint8_t data)
Program an 8 bit Byte to FLASH.
This performs all operations necessary to program an 8 bit byte to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] address Starting address in Flash.
[in] data byte to write
Definition at line 420 of file flash.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X8, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO8.
Referenced by flash_program().
void flash_program_double_word (uint32_t address, uint64_t data)
Program a 64 bit Word to FLASH.
This performs all operations necessary to program a 64 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] address Starting address in Flash.
[in] data Double word to write
Definition at line 335 of file flash.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X64, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO64.
void flash_program_half_word (uint32_t address, uint16_t data)
Program a Half Word to FLASH.
This performs all operations necessary to program a 16 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] address Starting address in Flash.
[in] data half word to write
Definition at line 395 of file flash.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X16, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO16.
void flash_program_option_bytes (uint32_t data)
Program the Option Bytes.
This performs all operations necessary to program the option bytes. The option bytes do not need to be erased first.
Parameters
[in] data value to be programmed.
Definition at line 467 of file flash.c.
References FLASH_OPTCR, FLASH_OPTCR_OPTLOCK, FLASH_OPTCR_OPTSTRT, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_program_word (uint32_t address, uint32_t data)
Program a 32 bit Word to FLASH.
This performs all operations necessary to program a 32 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] address Starting address in Flash.
[in] data word to write
Definition at line 365 of file flash.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X32, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO32.
void flash_set_ws (uint32_t ws)
Set the Number of Wait States.
Used to match the system clock to the FLASH memory access time. See the programming manual for more information on clock speed ranges. The latency must be changed to the appropriate value before any increase in clock speed, or after any decrease in clock speed.
Parameters
[in] ws values from flash_latency.
Definition at line 71 of file flash.c.
References FLASH_ACR, and FLASH_ACR_LATENCY_MASK.
Referenced by rcc_clock_setup_hse(), and rcc_clock_setup_hsi().
void flash_unlock (void)
Unlock the Flash Program and Erase Controller.
This enables write access to the Flash memory. It is locked by default on reset.
Definition at line 94 of file flash.c.
References FLASH_CR, FLASH_CR_LOCK, FLASH_KEYR, FLASH_KEYR_KEY1, and FLASH_KEYR_KEY2.
void flash_unlock_option_bytes (void)
Unlock the Option Byte Access.
This enables write access to the option bytes. It is locked by default on reset.
Definition at line 156 of file flash.c.
References FLASH_OPTCR, FLASH_OPTCR_OPTLOCK, FLASH_OPTKEYR, FLASH_OPTKEYR_KEY1, and FLASH_OPTKEYR_KEY2.
Referenced by flash_program_option_bytes().
void flash_wait_for_last_operation (void)
Wait until Last Operation has Ended.
This loops indefinitely until an operation (write or erase) has completed by testing the busy flag.
Definition at line 143 of file flash.c.
References flash_pipeline_stall(), FLASH_SR, and FLASH_SR_BSY.
Referenced by flash_erase_all_sectors(), flash_erase_sector(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), flash_program_option_bytes(), and flash_program_word().