libopencm3: dma_common.c File Reference
dma_common.c File Reference
#include <libopencm3/efm32/dma.h>
Macros
#define CHANNEL_SUPPORT_LOOP(ch) (((ch) == DMA_CH0) || ((ch) == DMA_CH1))
Functions
void dma_enable_with_privileged_access (void)
Enable DMA with privileged access.
void dma_enable_with_unprivileged_access (void)
Enable DMA with un-privileged access.
void dma_enable (void)
same as dma_enable_with_unprivileged_access()
void dma_disable (void)
Disable DMA.
void dma_set_desc_address (uint32_t desc_base)
Set channel's descriptor address.
bool dma_get_wait_on_request_flag (enum dma_ch ch)
Get channel wait on request status flag.
void dma_generate_software_request (enum dma_ch ch)
Generate a software request on channel.
void dma_enable_burst_only (enum dma_ch ch)
Enable channel burst only.
void dma_enable_single_and_burst (enum dma_ch ch)
Enable channel single and burst.
void dma_enable_periph_request (enum dma_ch ch)
Enable channel peripherial request.
void dma_disable_periph_request (enum dma_ch ch)
Disable channel peripherial request.
void dma_enable_channel (enum dma_ch ch)
Enable channel.
void dma_disable_channel (enum dma_ch ch)
Disable channel.
void dma_disable_alternate_structure (enum dma_ch ch)
Disable channel alternate structure.
void dma_enable_alternate_structure (enum dma_ch ch)
Enable channel alternate structure.
void dma_enable_priority (enum dma_ch ch)
Enable channel high priority.
void dma_disable_priority (enum dma_ch ch)
Disable channel high priority.
bool dma_get_bus_error_flag (void)
Get bus error flag.
void dma_clear_bus_error_flag (void)
Clear bus error flag.
bool dma_get_request_flag (enum dma_ch ch)
Get channel request flag.
bool dma_get_bus_error_interrupt_flag (void)
Get bus error interrupt flag.
bool dma_get_done_interrupt_flag (enum dma_ch ch)
Get channel done interrupt flag.
void dma_set_bus_error_interrupt_flag (void)
Set bus error interrupt flag.
void dma_set_done_interrupt_flag (enum dma_ch ch)
Set channel done interrupt flag.
void dma_clear_bus_error_interrupt_flag (void)
Clear bus error interrupt flag.
void dma_clear_done_interrupt_flag (enum dma_ch ch)
Clear channel done interrupt flag.
void dma_enable_bus_error_interrupt (void)
Enable bus error interrupt.
void dma_disable_bus_error_interrupt (void)
Disable bus error interrupt.
void dma_enable_done_interrupt (enum dma_ch ch)
Enable channel done interrupt.
void dma_disable_done_interrupt (enum dma_ch ch)
Disable channel done interrupt.
void dma_set_source (enum dma_ch ch, uint32_t source)
Set channel source.
void dma_set_signal (enum dma_ch ch, uint32_t signal)
Set channel source signal.
void dma_channel_reset (enum dma_ch ch)
Reset channel.
void dma_set_loop_count (enum dma_ch ch, uint16_t count)
Set channel loop width to (count + 1)
void dma_enable_loop (enum dma_ch ch)
Enable channel loop.
void dma_disable_loop (enum dma_ch ch)
Disable channel loop.
void dma_desc_set_dest_size (uint32_t desc_base, enum dma_ch ch, enum dma_mem size)
Set desination size.
void dma_desc_set_dest_inc (uint32_t desc_base, enum dma_ch ch, enum dma_mem inc)
Set destination increment.
void dma_desc_set_src_size (uint32_t desc_base, enum dma_ch ch, enum dma_mem size)
Set source size.
void dma_desc_set_src_inc (uint32_t desc_base, enum dma_ch ch, enum dma_mem inc)
Set source increment.
void dma_desc_set_r_power (uint32_t desc_base, enum dma_ch ch, enum dma_r_power r_power)
Set R Power.
void dma_desc_enable_next_useburst (uint32_t desc_base, enum dma_ch ch)
Enable next useburst.
void dma_desc_disable_next_useburst (uint32_t desc_base, enum dma_ch ch)
Disable next useburst.
void dma_desc_set_count (uint32_t desc_base, enum dma_ch ch, uint16_t count)
Set number (count) of transfer to be performed.
void dma_desc_set_user_data (uint32_t desc_base, enum dma_ch ch, uint32_t user_data)
Store user data field in channel descriptor.
uint32_t dma_desc_get_user_data (uint32_t desc_base, enum dma_ch ch)
Extract user data field from channel descriptor.
static uint32_t dma_calc_end_from_start (uint32_t start, uint8_t inc, uint16_t n_minus_1)
Calculate end from start address.
void dma_desc_set_src_address (uint32_t desc_base, enum dma_ch ch, uint32_t src_start)
Assign Source address to DMA Channel.
void dma_desc_set_dest_address (uint32_t desc_base, enum dma_ch ch, uint32_t dest_start)
Assign Destination address to DMA Channel.
void dma_desc_set_mode (uint32_t desc_base, enum dma_ch ch, enum dma_mode mode)
Set the channel mode ("Cycle control")
Macro Definition Documentation
#define CHANNEL_SUPPORT_LOOP (ch) (((ch) == DMA_CH0) || ((ch) == DMA_CH1))
Definition at line 22 of file dma_common.c.
Referenced by dma_channel_reset(), dma_disable_loop(), dma_enable_loop(), and dma_set_loop_count().
Function Documentation
static uint32_t dma_calc_end_from_start (uint32_t start, uint8_t inc, uint16_t n_minus_1) inline static
Calculate end from start address.
See "8.4.3.4 Address calculation" p68, EFM32LG-RM "d0183_Rev1.10"
Parameters
[in] start address to start of memory
[in] inc Increment (use DMA_MEM_*)
[in] n_minus_1 the number of transfers minus 1 (ie count - 1)
Returns
the calculate end address
Note
can be used to calculate {source, destination} end address
Definition at line 543 of file dma_common.c.
References DMA_MEM_BYTE, DMA_MEM_HALF_WORD, DMA_MEM_NONE, and DMA_MEM_WORD.
Referenced by dma_desc_set_dest_address(), and dma_desc_set_src_address().
void dma_channel_reset (enum dma_ch ch)
Reset channel.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 329 of file dma_common.c.
References CHANNEL_SUPPORT_LOOP, DMA_CHALTC, DMA_CHALTC_CHxSALTC, DMA_CHENC, DMA_CHENC_CHxSENC, DMA_CHPRIC, DMA_CHPRIC_CHxSPRIC, DMA_CHx_CTRL, DMA_IFC, DMA_IFC_CHxDONE, and DMA_LOOPx.
void dma_clear_bus_error_flag (void)
Clear bus error flag.
Definition at line 196 of file dma_common.c.
References DMA_ERRORC, and DMA_ERRORC_ERRORC.
void dma_clear_bus_error_interrupt_flag (void)
Clear bus error interrupt flag.
Definition at line 255 of file dma_common.c.
References DMA_IFC, and DMA_IFC_ERR.
void dma_clear_done_interrupt_flag (enum dma_ch ch)
Clear channel done interrupt flag.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 264 of file dma_common.c.
References DMA_IFC, and DMA_IFC_CHxDONE.
void dma_desc_disable_next_useburst (uint32_t desc_base, enum dma_ch ch)
Disable next useburst.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
Definition at line 486 of file dma_common.c.
References DMA_DESC_CH_CFG_NEXT_USEBURST, and DMA_DESC_CHx_CFG.
void dma_desc_enable_next_useburst (uint32_t desc_base, enum dma_ch ch)
Enable next useburst.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
Definition at line 475 of file dma_common.c.
References DMA_DESC_CH_CFG_NEXT_USEBURST, and DMA_DESC_CHx_CFG.
uint32_t dma_desc_get_user_data (uint32_t desc_base, enum dma_ch ch)
Extract user data field from channel descriptor.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
Returns
user data
Definition at line 526 of file dma_common.c.
References DMA_DESC_CHx_USER_DATA.
void dma_desc_set_count (uint32_t desc_base, enum dma_ch ch, uint16_t count)
Set number (count) of transfer to be performed.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] count Count
Definition at line 498 of file dma_common.c.
References DMA_DESC_CH_CFG_N_MINUS_1, DMA_DESC_CH_CFG_N_MINUS_1_MASK, and DMA_DESC_CHx_CFG.
void dma_desc_set_dest_address (uint32_t desc_base, enum dma_ch ch, uint32_t dest_start)
Assign Destination address to DMA Channel.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] dest_start Destination data start address
[in] this function use dma_desc_set_count() and dma_desc_set_dest_inc() set value to calculate the dest data end address from dest_start
Note
dma_desc_set_count() should be called first.
dma_desc_set_dest_inc() should be called first.
Definition at line 595 of file dma_common.c.
References dma_calc_end_from_start(), DMA_DESC_CH_CFG_DEST_INC_MASK, DMA_DESC_CH_CFG_DEST_INC_SHIFT, DMA_DESC_CH_CFG_N_MINUS_1_MASK, DMA_DESC_CH_CFG_N_MINUS_1_SHIFT, DMA_DESC_CHx_CFG, and DMA_DESC_CHx_DEST_DATA_END_PTR.
void dma_desc_set_dest_inc (uint32_t desc_base, enum dma_ch ch, enum dma_mem inc)
Set destination increment.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] inc Increment (use DMA_MEM_*)
Definition at line 412 of file dma_common.c.
References DMA_DESC_CH_CFG_DEST_INC, DMA_DESC_CH_CFG_DEST_INC_MASK, and DMA_DESC_CHx_CFG.
void dma_desc_set_dest_size (uint32_t desc_base, enum dma_ch ch, enum dma_mem size)
Set desination size.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] size Size (use DMA_MEM_*)
Definition at line 396 of file dma_common.c.
References DMA_DESC_CH_CFG_DEST_SIZE, DMA_DESC_CH_CFG_DEST_SIZE_MASK, and DMA_DESC_CHx_CFG.
void dma_desc_set_mode (uint32_t desc_base, enum dma_ch ch, enum dma_mode mode)
Set the channel mode ("Cycle control")
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] mode Mode (use DMA_MODE_*)
Definition at line 615 of file dma_common.c.
References DMA_DESC_CH_CFG_CYCLE_CTRL, DMA_DESC_CH_CFG_CYCLE_CTRL_MASK, and DMA_DESC_CHx_CFG.
void dma_desc_set_r_power (uint32_t desc_base, enum dma_ch ch, enum dma_r_power r_power)
Set R Power.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] r_power R Power (Use DMA_R_POWER_*)
Definition at line 460 of file dma_common.c.
References DMA_DESC_CH_CFG_R_POWER, DMA_DESC_CH_CFG_R_POWER_MASK, and DMA_DESC_CHx_CFG.
void dma_desc_set_src_address (uint32_t desc_base, enum dma_ch ch, uint32_t src_start)
Assign Source address to DMA Channel.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] src_start Source data start address
[in] this function use dma_desc_set_count() and dma_desc_set_src_inc() set value to calculate the src data end address from src_start
Note
dma_desc_set_count() should be called first.
dma_desc_set_src_inc() should be called first.
Definition at line 571 of file dma_common.c.
References dma_calc_end_from_start(), DMA_DESC_CH_CFG_N_MINUS_1_MASK, DMA_DESC_CH_CFG_N_MINUS_1_SHIFT, DMA_DESC_CH_CFG_SRC_INC_MASK, DMA_DESC_CH_CFG_SRC_INC_SHIFT, DMA_DESC_CHx_CFG, and DMA_DESC_CHx_SRC_DATA_END_PTR.
void dma_desc_set_src_inc (uint32_t desc_base, enum dma_ch ch, enum dma_mem inc)
Set source increment.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] inc Increment (use DMA_MEM_*)
Definition at line 444 of file dma_common.c.
References DMA_DESC_CH_CFG_SRC_INC, DMA_DESC_CH_CFG_SRC_INC_MASK, and DMA_DESC_CHx_CFG.
void dma_desc_set_src_size (uint32_t desc_base, enum dma_ch ch, enum dma_mem size)
Set source size.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] size Size (use DMA_MEM_*)
Definition at line 428 of file dma_common.c.
References DMA_DESC_CH_CFG_SRC_SIZE, DMA_DESC_CH_CFG_SRC_SIZE_MASK, and DMA_DESC_CHx_CFG.
void dma_desc_set_user_data (uint32_t desc_base, enum dma_ch ch, uint32_t user_data)
Store user data field in channel descriptor.
Parameters
[in] desc_base start of memory location that contain channel descriptor
[in] ch Channel (use DMA_CHx)
[in] user_data User data
Definition at line 513 of file dma_common.c.
References DMA_DESC_CHx_USER_DATA.
void dma_disable (void)
Disable DMA.
Definition at line 54 of file dma_common.c.
References DMA_CONFIG.
void dma_disable_alternate_structure (enum dma_ch ch)
Disable channel alternate structure.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 151 of file dma_common.c.
References DMA_CHALTC, and DMA_CHALTC_CHxSALTC.
void dma_disable_bus_error_interrupt (void)
Disable bus error interrupt.
Definition at line 280 of file dma_common.c.
References DMA_IEN, and DMA_IEN_ERR.
void dma_disable_channel (enum dma_ch ch)
Disable channel.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 142 of file dma_common.c.
References DMA_CHENC, and DMA_CHENC_CHxSENC.
void dma_disable_done_interrupt (enum dma_ch ch)
Disable channel done interrupt.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 298 of file dma_common.c.
References DMA_IEN, and DMA_IEN_CHxDONE.
void dma_disable_loop (enum dma_ch ch)
Disable channel loop.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 380 of file dma_common.c.
References CHANNEL_SUPPORT_LOOP, DMA_LOOP_EN, and DMA_LOOPx.
void dma_disable_periph_request (enum dma_ch ch)
Disable channel peripherial request.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 124 of file dma_common.c.
References DMA_CHREQMASKS, and DMA_CHREQMASKS_CHxSREQMASKS.
void dma_disable_priority (enum dma_ch ch)
Disable channel high priority.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 178 of file dma_common.c.
References DMA_CHPRIC, and DMA_CHPRIC_CHxSPRIC.
void dma_enable (void)
same as dma_enable_with_unprivileged_access()
See also
dma_enable_with_unprivileged_access()
Definition at line 46 of file dma_common.c.
References dma_enable_with_unprivileged_access().
void dma_enable_alternate_structure (enum dma_ch ch)
Enable channel alternate structure.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 160 of file dma_common.c.
References DMA_CHALTS, and DMA_CHALTS_CHxSALTS.
void dma_enable_burst_only (enum dma_ch ch)
Enable channel burst only.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 97 of file dma_common.c.
References DMA_CHUSEBURSTS, and DMA_CHUSEBURSTS_CHxSUSEBURSTS.
void dma_enable_bus_error_interrupt (void)
Enable bus error interrupt.
Definition at line 272 of file dma_common.c.
References DMA_IEN, and DMA_IEN_ERR.
void dma_enable_channel (enum dma_ch ch)
Enable channel.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 133 of file dma_common.c.
References DMA_CHENS, and DMA_CHENS_CHxSENS.
void dma_enable_done_interrupt (enum dma_ch ch)
Enable channel done interrupt.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 289 of file dma_common.c.
References DMA_IEN, and DMA_IEN_CHxDONE.
void dma_enable_loop (enum dma_ch ch)
Enable channel loop.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 367 of file dma_common.c.
References CHANNEL_SUPPORT_LOOP, DMA_LOOP_EN, and DMA_LOOPx.
void dma_enable_periph_request (enum dma_ch ch)
Enable channel peripherial request.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 115 of file dma_common.c.
References DMA_CHREQMASKC, and DMA_CHREQMASKC_CHxSREQMASKC.
void dma_enable_priority (enum dma_ch ch)
Enable channel high priority.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 169 of file dma_common.c.
References DMA_CHPRIS, and DMA_CHPRIS_CHxSPRIC.
void dma_enable_single_and_burst (enum dma_ch ch)
Enable channel single and burst.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 106 of file dma_common.c.
References DMA_CHUSEBURSTC, and DMA_CHUSEBURSTC_CHxSUSEBURSTC.
void dma_enable_with_privileged_access (void)
Enable DMA with privileged access.
See also
dma_enable_with_unprivileged_access()
Definition at line 28 of file dma_common.c.
References DMA_CONFIG, DMA_CONFIG_CHPROT, and DMA_CONFIG_EN.
void dma_enable_with_unprivileged_access (void)
Enable DMA with un-privileged access.
See also
dma_enable_with_privileged_access()
Definition at line 37 of file dma_common.c.
References DMA_CONFIG, and DMA_CONFIG_EN.
Referenced by dma_enable().
void dma_generate_software_request (enum dma_ch ch)
Generate a software request on channel.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 88 of file dma_common.c.
References DMA_CHSWREQ, and DMA_CHSWREQ_CHxSWREQ.
bool dma_get_bus_error_flag (void)
Get bus error flag.
Return values
true if flag is set
false if flag is not set
Definition at line 188 of file dma_common.c.
References DMA_ERRORC, and DMA_ERRORC_ERRORC.
bool dma_get_bus_error_interrupt_flag (void)
Get bus error interrupt flag.
Return values
true if flag is set
false if flag is not set
Definition at line 218 of file dma_common.c.
References DMA_IF, and DMA_IF_ERR.
bool dma_get_done_interrupt_flag (enum dma_ch ch)
Get channel done interrupt flag.
Parameters
[in] ch Channel (use DMA_CHx)
Return values
true if flag is set
false if flag is not set
Definition at line 230 of file dma_common.c.
References DMA_IF, and DMA_IF_CHxDONE.
bool dma_get_request_flag (enum dma_ch ch)
Get channel request flag.
Parameters
[in] ch Channel (use DMA_CHx)
Return values
true if flag is set
false if flag is not set
Definition at line 207 of file dma_common.c.
References DMA_CHREQSTATUS, and DMA_CHREQSTATUS_CHxSREQSTATUS.
bool dma_get_wait_on_request_flag (enum dma_ch ch)
Get channel wait on request status flag.
Return values
true if flag is set
false if flag is not set
Definition at line 78 of file dma_common.c.
References DMA_CHWAITSTATUS, and DMA_CHWAITSTATUS_CHxWAITSTATUS.
void dma_set_bus_error_interrupt_flag (void)
Set bus error interrupt flag.
Definition at line 238 of file dma_common.c.
References DMA_IFS, and DMA_IFS_ERR.
void dma_set_desc_address (uint32_t desc_base)
Set channel's descriptor address.
Parameters
[in] desc_base Address of channel's descriptor address
Note
desc_base 8LSB's should be 0x00
Definition at line 64 of file dma_common.c.
References DMA_CTRLBASE.
void dma_set_done_interrupt_flag (enum dma_ch ch)
Set channel done interrupt flag.
Parameters
[in] ch Channel (use DMA_CHx)
Definition at line 247 of file dma_common.c.
References DMA_IFS, and DMA_IFS_CHxDONE.
void dma_set_loop_count (enum dma_ch ch, uint16_t count)
Set channel loop width to (count + 1)
Parameters
[in] ch Channel (use DMA_CHx)
[in] count Count
Note
count is expected to be equal to (n_minus_1 + 1)
Definition at line 353 of file dma_common.c.
References CHANNEL_SUPPORT_LOOP, DMA_LOOP_WIDTH, DMA_LOOP_WIDTH_MASK, and DMA_LOOPx.
void dma_set_signal (enum dma_ch ch, uint32_t signal)
Set channel source signal.
Parameters
[in] ch Channel (use DMA_CHx)
[in] signal Signal (use DMA_CH_CTRL_SIGSEL_*)
Definition at line 319 of file dma_common.c.
References DMA_CH_CTRL_SIGSEL_MASK, and DMA_CHx_CTRL.
void dma_set_source (enum dma_ch ch, uint32_t source)
Set channel source.
Parameters
[in] ch Channel (use DMA_CHx)
[in] source Source (use DMA_CH_CTRL_SOURCESEL_*)
Definition at line 308 of file dma_common.c.
References DMA_CH_CTRL_SOURCESEL_MASK, and DMA_CHx_CTRL.