libopencm3: Flash_file
Flash_file
Functions
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
void flash_set_ws (uint32_t ws)
Set the Number of Wait States.
void flash_unlock_pecr (void)
Unlock primary access to the flash control/erase block You must call this before using any of the low level routines yourself.
void flash_lock_pecr (void)
void flash_unlock_progmem (void)
Unlock program memory itself.
void flash_lock_progmem (void)
void flash_unlock_option_bytes (void)
Unlock option bytes.
void flash_lock_option_bytes (void)
void flash_unlock (void)
Unlock all segments of flash.
void flash_lock (void)
Lock all segments of flash.
void eeprom_program_word (uint32_t address, uint32_t data)
Write a word to eeprom.
void eeprom_program_words (uint32_t address, uint32_t *data, int length_in_words)
Write a block of words to eeprom.
Detailed Description
Function Documentation
void eeprom_program_word (uint32_t address, uint32_t data)
Write a word to eeprom.
Parameters
address assumed to be in the eeprom space, no checking
data word to write
Definition at line 158 of file flash_common_l01.c.
References flash_lock_pecr(), FLASH_PECR, FLASH_PECR_FTDW, flash_unlock_pecr(), and MMIO32.
void eeprom_program_words (uint32_t address, uint32_t * data, int length_in_words)
Write a block of words to eeprom.
Writes a block of words to EEPROM at the requested address, erasing if necessary, and locking afterwards. Only wordwise writing is safe for writing any value
Parameters
[in] address must point to EEPROM space, no checking!
[in] data pointer to data to write
[in] length_in_words size of of data in WORDS!
Definition at line 177 of file flash_common_l01.c.
References flash_lock_pecr(), FLASH_PECR, FLASH_PECR_FTDW, FLASH_SR, FLASH_SR_BSY, flash_unlock_pecr(), and MMIO32.
void flash_lock (void)
Lock all segments of flash.
Definition at line 146 of file flash_common_l01.c.
References flash_lock_option_bytes(), flash_lock_pecr(), and flash_lock_progmem().
void flash_lock_option_bytes (void)
Definition at line 128 of file flash_common_l01.c.
References FLASH_PECR, and FLASH_PECR_OPTLOCK.
Referenced by flash_lock().
void flash_lock_pecr (void)
Definition at line 94 of file flash_common_l01.c.
References FLASH_PECR, and FLASH_PECR_PELOCK.
Referenced by eeprom_program_word(), eeprom_program_words(), and flash_lock().
void flash_lock_progmem (void)
Definition at line 111 of file flash_common_l01.c.
References FLASH_PECR, and FLASH_PECR_PRGLOCK.
Referenced by flash_lock().
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
Note carefully the restrictions under which the prefetch buffer may be set to disabled. See the reference and programming manuals for details.
Definition at line 55 of file flash_common_l01.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the restrictions under which the prefetch buffer may be enabled or disabled. Prefetch is only available when 64-bit access is enabled.
Definition at line 43 of file flash_common_l01.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
Referenced by rcc_clock_setup_pll().
void flash_set_ws (uint32_t ws)
Set the Number of Wait States.
Used to match the system clock to the FLASH memory access time. See the programming manual for more information on clock speed and voltage ranges. The latency must be changed to the appropriate value before any increase in clock speed, or after any decrease in clock speed. A latency setting of zero only applies if 64-bit mode is not used.
Parameters
[in] ws values from FLASH Wait States.
Definition at line 72 of file flash_common_l01.c.
References FLASH_ACR.
Referenced by rcc_clock_setup_pll().
void flash_unlock (void)
Unlock all segments of flash.
Definition at line 136 of file flash_common_l01.c.
References flash_unlock_option_bytes(), flash_unlock_pecr(), and flash_unlock_progmem().
void flash_unlock_option_bytes (void)
Unlock option bytes.
Writes the magic sequence to unlock the option bytes, you must have already unlocked access to this register!
See also
flash_unlock_pecr
Definition at line 122 of file flash_common_l01.c.
References FLASH_OPTKEYR, FLASH_OPTKEYR_OPTKEY1, and FLASH_OPTKEYR_OPTKEY2.
Referenced by flash_unlock().
void flash_unlock_pecr (void)
Unlock primary access to the flash control/erase block You must call this before using any of the low level routines yourself.
See also
flash_unlock
Definition at line 88 of file flash_common_l01.c.
References FLASH_PEKEYR, FLASH_PEKEYR_PEKEY1, and FLASH_PEKEYR_PEKEY2.
Referenced by eeprom_program_word(), eeprom_program_words(), and flash_unlock().
void flash_unlock_progmem (void)
Unlock program memory itself.
Writes the magic sequence to unlock the program memory you must have already unlocked access to this register!
See also
flash_unlock_pecr
Definition at line 105 of file flash_common_l01.c.
References FLASH_PRGKEYR, FLASH_PRGKEYR_PRGKEY1, and FLASH_PRGKEYR_PRGKEY2.
Referenced by flash_unlock().