libopencm3: st_usbfs_v2.c File Reference
st_usbfs_v2.c File Reference
#include <libopencm3/cm3/common.h>
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/tools.h>
#include <libopencm3/stm32/st_usbfs.h>
#include <libopencm3/usb/usbd.h>
#include "../usb/usb_private.h"
#include "common/st_usbfs_core.h"
Functions
static usbd_device * st_usbfs_v2_usbd_init (void)
Initialize the USB device controller hardware of the STM32.
void st_usbfs_copy_to_pm (volatile void *vPM, const void *buf, uint16_t len)
void st_usbfs_copy_from_pm (void *buf, const volatile void *vPM, uint16_t len)
Copy a data buffer from packet memory.
Variables
const struct _usbd_driver st_usbfs_v2_usb_driver
Function Documentation
void st_usbfs_copy_from_pm (void * buf, const volatile void * vPM, uint16_t len)
Copy a data buffer from packet memory.
Parameters
buf Destination pointer for data buffer.
vPM Source pointer into packet memory.
len Number of bytes to copy.
Definition at line 80 of file st_usbfs_v2.c.
Referenced by st_usbfs_ep_read_packet().
void st_usbfs_copy_to_pm (volatile void * vPM, const void * buf, uint16_t len)
Definition at line 59 of file st_usbfs_v2.c.
Referenced by st_usbfs_ep_write_packet().
static usbd_device * st_usbfs_v2_usbd_init (void) static
Initialize the USB device controller hardware of the STM32.
Definition at line 45 of file st_usbfs_v2.c.
References rcc_periph_clock_enable(), RCC_USB, SET_REG, st_usbfs_dev, USB_BCDR_DPPU, USB_BCDR_REG, USB_BTABLE_REG, USB_CNTR_CTRM, USB_CNTR_REG, USB_CNTR_RESETM, USB_CNTR_SUSPM, USB_CNTR_WKUPM, and USB_ISTR_REG.